# Installed nvim using Pre-built archives
# The Releases page provides pre-built binaries for Linux systems.
update:
  curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
  sudo rm -rf /opt/nvim
  sudo tar -C /opt -xzf nvim-linux64.tar.gz
  export PATH="$PATH:/opt/nvim-linux64/bin"
